spring.application.name=api_rest_RedSocial

# Configuración del DataSource (Corregido driver_class a driver-class-name)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/redsocial_db
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA / Hibernate (IMPORTANTE: deben llevar el prefijo spring.jpa)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de creación de tablas (Corregido el nombre de la propiedad)
spring.jpa.hibernate.ddl-auto=update

# Dialecto (Opcional en versiones modernas, pero corregido el prefijo)
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Jackson
spring.jackson.serialization.fail-on-empty-beans=false